/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Model.Chitietsanpham;
import Model.Sanpham;
import bus.chitietsanphamBUS;
import bus.hanghoaBUS;
import static java.lang.Integer.parseInt;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class chitietsanpham extends javax.swing.JFrame {
    DefaultTableModel Model;
    /**
     * Creates new form chitietsanpham
     */
    static Chitietsanpham sp = new Chitietsanpham();
    public static Chitietsanpham getSp() {
        return sp;
    }
     public static void setSp(Chitietsanpham sp) {
        chitietsanpham.sp = sp;
    }
    public chitietsanpham() throws Exception {
        initComponents();
        process(false);
        chitietsanphamBUS bus = new chitietsanphamBUS();
        if(chitietsanphamBUS.getDSSP()==null)
           bus.docDSSP();
       Vector header = new Vector();
        header.add("Mã sản phẩm");
        header.add("Công dụng");
        header.add("Chiều dài");
        header.add("Chiều rộng");
        header.add("Chiều cao");
        header.add("trọng lượng");
        Model = new DefaultTableModel(header,0);
        for(Chitietsanpham sp: chitietsanphamBUS.getDSSP()){
            Vector row = new Vector();
            row.add(sp.getMaSP());
            row.add(sp.getCongdungSP());
            row.add(sp.getChieudaiSP());
            row.add(sp.getChieurongSP());
            row.add(sp.getChieucaoSP());
            row.add(sp.getTrongluongSP());
            Model.addRow(row);
        }
        jTable1.setModel(Model);
    }
    public void process(boolean b){
      this.jButton4.setEnabled(b);
      this.jButton5.setEnabled(b);
      this.jButton6.setEnabled(b);
  }
    public void show2(){
        process(false);
         this.jButton4.setEnabled(false);
       this.jTextField1.setText(null);
       this.jTextField2.setText(null);
       this.jTextField3.setText(null);
       this.jTextField4.setText(null);
       this.jTextField5.setText(null);
       this.jTextField6.setText(null);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Back.png"))); // NOI18N
        jButton1.setText("Trở về");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 152, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã sản phẩm:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 99, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Công dụng:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 126, 33));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Chiều dài (cm):");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 143, 36));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 78, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Chiểu rộng (cm):");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, 30));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 76, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Chiều cao (cm):");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, 35));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 80, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Trọng lượng (kg):");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, 30));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 78, 30));

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setForeground(new java.awt.Color(255, 0, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTable1.setSelectionForeground(new java.awt.Color(255, 0, 153));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 452, 632, 194));

        jButton3.setBackground(new java.awt.Color(255, 0, 153));
        jButton3.setText("Nhập mới");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 103, 40));

        jButton2.setBackground(new java.awt.Color(255, 0, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Refresh-icon.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 338, 106, 89));

        jButton4.setBackground(new java.awt.Color(255, 0, 153));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Add.png"))); // NOI18N
        jButton4.setText("Thêm");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 338, 125, 89));

        jButton5.setBackground(new java.awt.Color(255, 0, 153));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Change.png"))); // NOI18N
        jButton5.setText("Sửa");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 338, 124, 89));

        jButton6.setBackground(new java.awt.Color(255, 0, 153));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Delete.png"))); // NOI18N
        jButton6.setText("Xoá");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 338, 117, 89));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 290, 559, 30));

        jButton7.setBackground(new java.awt.Color(255, 0, 153));
        jButton7.setText("Tìm kiếm");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 290, 120, 30));

        jButton8.setBackground(new java.awt.Color(255, 0, 153));
        jButton8.setText("Quay lai");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 290, 50, 30));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chi tiết sản phẩm");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 153), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          
        hanghoa h = null;
        try {
           h = new hanghoa();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(hanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setVisible(false);
       h.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       process(false);
       this.jButton4.setEnabled(true);
       this.jTextField1.setText(null);
       this.jTextField2.setText(null);
       this.jTextField3.setText(null);
       this.jTextField4.setText(null);
       this.jTextField5.setText(null);
       this.jTextField6.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
       this.jTextField1.setText("");
       this.jTextField2.setText("");
       this.jTextField3.setText("");
       this.jTextField4.setText("");
       this.jTextField5.setText("");
       this.jTextField6.setText("");
       show2();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        chitietsanphamBUS bus = new chitietsanphamBUS();
        Chitietsanpham sp = new Chitietsanpham();
        
        if("".equals(jTextField1.getText().trim())){
           JOptionPane.showMessageDialog(this, "Mã sản phẩm không được rỗng");
           jTextField1.requestFocus();
       }
        else
            try{
                 if(!bus.vaildID(jTextField1.getText())){
                   JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại");
                   jTextField1.requestFocus();
               }
            else
                  if("".equals(jTextField2.getText().trim())){
                    JOptionPane.showMessageDialog(this,"Công dụng không được rỗng" );
                    jTextField2.requestFocus();
            }
                 else
                    if("".equals(jTextField3.getText().trim())){
                    JOptionPane.showMessageDialog(this,"Chiều dài không được rỗng" );
                    jTextField3.requestFocus();
                      
            }
                 else
                     if(!bus.validNumber(jTextField3.getText())){
                        JOptionPane.showMessageDialog(this,"Chiều dài không được chứa chữ cái và phải là số dương!");
                        jTextField3.requestFocus();
                    }
                 else
                     if("".equals(jTextField4.getText().trim())){
                    JOptionPane.showMessageDialog(this,"Chiều rộng không được rỗng" );
                    jTextField4.requestFocus(); 
                     }
                 else
                       if(!bus.validNumber(jTextField4.getText())){
                        JOptionPane.showMessageDialog(this,"Chiều rộng không được chứa chữ cái và phải là số dương!");
                        jTextField4.requestFocus();
                    }   
                 else
                       if("".equals(jTextField5.getText().trim())){
                    JOptionPane.showMessageDialog(this,"Chiều cao không được rỗng" );
                    jTextField5.requestFocus(); 
                     }  
                 else
                       if(!bus.validNumber(jTextField5.getText())){
                        JOptionPane.showMessageDialog(this,"Chiều cao không được chứa chữ cái và phải là số dương!");
                        jTextField5.requestFocus();
                    }      
                 else
                         if("".equals(jTextField6.getText().trim())){
                    JOptionPane.showMessageDialog(this,"Trọng lượng không được rỗng" );
                    jTextField6.requestFocus(); 
                     } 
                 else
                        if(!bus.validNumber(jTextField6.getText())){
                        JOptionPane.showMessageDialog(this,"Trọng lượng không được chứa chữ cái và phải là số dương!");
                        jTextField6.requestFocus();
                    }           
                 else
                        {
                        sp.setMaSP(jTextField1.getText());
                        sp.setCongdungSP(jTextField2.getText());
                        sp.setChieudaiSP(parseInt(jTextField3.getText()));
                        sp.setChieurongSP(parseInt(jTextField4.getText()));
                        sp.setChieucaoSP(parseInt(jTextField5.getText()));
                        sp.setTrongluongSP(parseInt(jTextField6.getText()));
                         Model.addRow(new Object[]{
           jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText()
       });
                        }
                 try{
                     bus.them(sp);
                 } catch (Exception ex) {
                java.util.logging.Logger.getLogger(chitietsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);    
                 }
           }catch (Exception ex){
               java.util.logging.Logger.getLogger(hanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        process(true);
        this.jButton4.setEnabled(false);
        this.jTextField1.setEnabled(false);
     int row = jTable1.getSelectedRow();
       String id = jTable1.getValueAt(row,0).toString();
       String cd = jTable1.getValueAt(row,1).toString();
       String cdd = jTable1.getValueAt(row,2).toString();
       String cr = jTable1.getValueAt(row,3).toString();
       String cc = jTable1.getValueAt(row,4).toString();
       String tl = jTable1.getValueAt(row,5).toString();
       
        
        jTextField1.setText(id);
        jTextField2.setText(cd);
        jTextField3.setText(cdd);
        jTextField4.setText(cr);
        jTextField5.setText(cc);
        jTextField6.setText(tl);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        chitietsanphamBUS bus = new chitietsanphamBUS();
        Chitietsanpham sp = new Chitietsanpham();
        
        if("".equals(jTextField1.getText().trim())){
           JOptionPane.showMessageDialog(this, "Mã sản phẩm không được rỗng");
           jTextField1.requestFocus();
       }
        else
                            
                  if("".equals(jTextField2.getText().trim())){
                    JOptionPane.showMessageDialog(this,"Công dụng không được rỗng" );
                    jTextField2.requestFocus();
            }
                 else
                    if("".equals(jTextField3.getText().trim())){
                    JOptionPane.showMessageDialog(this,"Chiều dài không được rỗng" );
                    jTextField3.requestFocus();
                      
            }
                 else
                     if(!bus.validNumber(jTextField3.getText())){
                        JOptionPane.showMessageDialog(this,"Chiều dài không được chứa chữ cái và phải là số dương!");
                        jTextField3.requestFocus();
                    }
                 else
                     if("".equals(jTextField4.getText().trim())){
                    JOptionPane.showMessageDialog(this,"Chiều rộng không được rỗng" );
                    jTextField4.requestFocus(); 
                     }
                 else
                       if(!bus.validNumber(jTextField4.getText())){
                        JOptionPane.showMessageDialog(this,"Chiều rộng không được chứa chữ cái và phải là số dương!");
                        jTextField4.requestFocus();
                    }   
                 else
                       if("".equals(jTextField5.getText().trim())){
                    JOptionPane.showMessageDialog(this,"Chiều cao không được rỗng" );
                    jTextField5.requestFocus(); 
                     }  
                 else
                       if(!bus.validNumber(jTextField5.getText())){
                        JOptionPane.showMessageDialog(this,"Chiều cao không được chứa chữ cái và phải là số dương!");
                        jTextField5.requestFocus();
                    }      
                 else
                         if("".equals(jTextField6.getText().trim())){
                    JOptionPane.showMessageDialog(this,"Trọng lượng không được rỗng" );
                    jTextField6.requestFocus(); 
                     } 
                 else
                        if(!bus.validNumber(jTextField6.getText())){
                        JOptionPane.showMessageDialog(this,"Trọng lượng không được chứa chữ cái và phải là số dương!");
                        jTextField6.requestFocus();
                    }           
                 else
                        {
                        sp.setMaSP(jTextField1.getText());
                        sp.setCongdungSP(jTextField2.getText());
                        sp.setChieudaiSP(parseInt(jTextField3.getText()));
                        sp.setChieurongSP(parseInt(jTextField4.getText()));
                        sp.setChieucaoSP(parseInt(jTextField5.getText()));
                        sp.setTrongluongSP(parseInt(jTextField6.getText()));
                        }
                   
                try{
                    bus.sua(sp);
                      Vector header = new Vector(); jTable1.getModel();
         header.add("Mã sản phẩm");
         header.add("Công dụng");
         header.add("Chiều dài");
         header.add("Chiều rộng");
         header.add("Chiều cao");
         header.add("trọng lượng");
        
        Model = new DefaultTableModel(header,0);
        for(Chitietsanpham spt: chitietsanphamBUS.getDSSP()){
            Vector row = new Vector();
            row.add(spt.getMaSP());
            row.add(spt.getCongdungSP());
            row.add(spt.getChieudaiSP());
            row.add(spt.getChieurongSP());
            row.add(spt.getChieucaoSP());
            row.add(spt.getTrongluongSP());
            Model.addRow(row);
        }
        jTable1.setModel(Model);
                }catch (Exception ex){
                        java.util.logging.Logger.getLogger(chitietsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
            
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          Model = (DefaultTableModel) jTable1.getModel();
        
        chitietsanphamBUS bus = new chitietsanphamBUS();
        
        int vitri = jTable1.getSelectedRow();
            
        if(vitri == -1) 
           JOptionPane.showMessageDialog(null, "Chưa chọn dòng cần xóa!");
        else{
            if(JOptionPane.showConfirmDialog(null,"Bạn muốn xóa sản phẩm này?","Xác nhận xóa",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION ){
           Model.removeRow(vitri);

                try {
                    bus.xoa(vitri);
                } catch (Exception ex) {
                    java.util.logging.Logger.getLogger(hanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        chitietsanphamBUS bus = new chitietsanphamBUS();
        ArrayList<Chitietsanpham> KetQua = new ArrayList<>();
        
        if(chitietsanphamBUS.getDSSP()== null)

                try {
                    bus.docDSSP();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(chitietsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        String key = jTextField7.getText();

        try {
            KetQua = bus.timKiemTheoMaTenSP(key);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(hanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        
        Vector header = new Vector();
        header.add("Mã sản phẩm");
        header.add("Công dụng");
        header.add("Chiều dài");
        header.add("Chiều rộng");
        header.add("Chiều cao");
        header.add("trọng lượng");
        
        Model = new DefaultTableModel(header,0);
        
        for(Chitietsanpham sp : KetQua){
            Vector row = new Vector();
            row.add(sp.getMaSP());
            row.add(sp.getCongdungSP());
            row.add(sp.getChieudaiSP());
            row.add(sp.getChieurongSP());
            row.add(sp.getChieucaoSP());
            row.add(sp.getTrongluongSP());
            Model.addRow(row);
            }
        jTable1.setModel(Model);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        chitietsanpham h = null;
        try {
            h = new chitietsanpham();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(chitietsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        h.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed


        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chitietsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chitietsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chitietsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chitietsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new chitietsanpham().setVisible(true);
                } catch (Exception ex) {
                    java.util.logging.Logger.getLogger(chitietsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
