/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Model.Sanpham;
import bus.hanghoaBUS;
import dao.hanghoaDAO;
import java.awt.event.KeyEvent;
import static java.lang.Double.parseDouble;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import static java.lang.Long.parseLong;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class hanghoa extends javax.swing.JFrame {
    DefaultTableModel Model;
    static Sanpham sp = new Sanpham();
    public static Sanpham getSP(){
        return sp;
    }
    public static void setSP(Sanpham sp){
        hanghoa.sp=sp;
    }
   public class myTableModel extends AbstractTableModel{

        @Override
        public int getRowCount() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public int getColumnCount() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
       public boolean isCell(int row, int col){
           return false;
       }
   }
   
    /**
     * Creates new form hanghoa
     * @throws java.lang.Exception
     */
    public hanghoa() throws Exception {
        initComponents();
        process(false);
        
        hanghoaBUS bus = new hanghoaBUS();
        if(hanghoaBUS.getDSSP()==null)
           bus.docDSSP();
       Vector header = new Vector();
        header.add("Mã sản phẩm");
        header.add("Tên sản phẩm");
        header.add("Số lượng");
        header.add("Đơn giá");
        header.add("Bảo hành");
        
        Model = new DefaultTableModel(header,0);
        for(Sanpham sp: hanghoaBUS.getDSSP()){
            Vector row = new Vector();
            row.add(sp.getMaSanpham());
            row.add(sp.getTenSanpham());
            row.add(sp.getSoluongSanpham());
            row.add(sp.getDongiaSanpham());
            row.add(sp.getBaohanhSanpham());
            Model.addRow(row);
        }
        jTable1.setModel(Model);
        
    }
  public void process(boolean b){
      this.jButton2.setEnabled(b);
      this.jButton7.setEnabled(b);
      this.jButton8.setEnabled(b);
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sản phẩm");
        setBackground(new java.awt.Color(51, 255, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Back.png"))); // NOI18N
        jButton1.setText("Hệ thống");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 4, 207, 81));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý sản phẩm");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 720, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã sản phẩm:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 104, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tên sản phẩm:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField2.setActionCommand("<Not Set>");
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 137, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Số lượng:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 75, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Đơn giá:");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 128, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Bảo hành:");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 170, 93, 30));

        jButton2.setBackground(new java.awt.Color(255, 0, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Add.png"))); // NOI18N
        jButton2.setText("Thêm");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 120, 80));

        jButton7.setBackground(new java.awt.Color(255, 0, 153));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Change.png"))); // NOI18N
        jButton7.setText("Sửa");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 120, 80));

        jButton8.setBackground(new java.awt.Color(255, 0, 153));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Delete.png"))); // NOI18N
        jButton8.setText("Xoá");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 120, 80));

        jButton9.setBackground(new java.awt.Color(255, 0, 153));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Save.png"))); // NOI18N
        jButton9.setText("Nâng cao");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, 120, 80));

        jButton11.setBackground(new java.awt.Color(255, 0, 153));
        jButton11.setForeground(new java.awt.Color(204, 255, 153));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Refresh-icon.png"))); // NOI18N
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 120, 80));

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 0, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Bảo hành"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 780, 150));

        jButton3.setBackground(new java.awt.Color(255, 0, 153));
        jButton3.setText("Nhập mới");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 113, 110, 40));

        jTextField6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 680, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 153));
        jButton4.setText("Tìm kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 80, 30));

        jButton5.setBackground(new java.awt.Color(255, 0, 153));
        jButton5.setText("Quay lại");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, 80, 30));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        trangchu ct = new trangchu();
        this.setVisible(false);
        ct.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        process(true);
        this.jButton2.setEnabled(false);
         this.jTextField1.setEnabled(false);
     int row = jTable1.getSelectedRow();
       String id = jTable1.getValueAt(row,0).toString();
       String ten = jTable1.getValueAt(row,1).toString();
       String soluong = jTable1.getValueAt(row,2).toString();
       String dongia = jTable1.getValueAt(row,3).toString();
       String baohanh = jTable1.getValueAt(row,4).toString();
       
        
        jTextField1.setText(id);
        jTextField2.setText(ten);
        jTextField3.setText(soluong);
        jTextField4.setText(dongia);
        jTextField5.setText(baohanh);
    }//GEN-LAST:event_jTable1MouseClicked
   
    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTable1KeyReleased
    public void show1(){
        process(false);
       this.jButton2.setEnabled(false);
       this.jTextField1.setText(null);
       this.jTextField2.setText(null);
       this.jTextField3.setText(null);
       this.jTextField4.setText(null);
       this.jTextField5.setText(null);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       hanghoaBUS hhb = new hanghoaBUS();
       Sanpham sp = new Sanpham();
      
       if("".equals(jTextField1.getText().trim())){
           JOptionPane.showMessageDialog(this, "Tên mã phẩm không được rỗng");
           jTextField1.requestFocus();
       }
       
       else 
           try{
               if("".equals(jTextField2.getText().trim())){
           JOptionPane.showMessageDialog(this,"Tên sản phẩm không được rỗng" );
            }
          else
               if(!hhb.vaildID(jTextField1.getText())){
                   JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại");
                   jTextField1.requestFocus();
               }
             else
                if(!hhb.validName(jTextField2.getText())){
                       JOptionPane.showMessageDialog(this, "Tên sản phẩm đã tồn tại");
                   }
                else 
                    if(jTextField3.getText().trim().equals("")){
                        JOptionPane.showMessageDialog(this, "Số lượng không được rỗng!");
                        jTextField3.requestFocus();
                    }
               else
                    if(!hhb.validNumber(jTextField3.getText())){
                         JOptionPane.showMessageDialog(this,"Số lượng sản phẩm không được chứa chữ cái và phải là số dương!");
                         jTextField3.requestFocus();
                    }
               else
                    if(jTextField4.getText().trim().equals("")){
                       JOptionPane.showMessageDialog(this, "Số lượng không được rỗng!");
                        jTextField4.requestFocus();
                    }
               else
                    if(!hhb.validNumber(jTextField4.getText())){
                        JOptionPane.showMessageDialog(this,"Đơn giá sản phẩm không được chứa chữ cái và phải là số dương!");
                        jTextField4.requestFocus();
                    }
               else
                    if(!hhb.validNumber(jTextField5.getText())){
                        JOptionPane.showMessageDialog(this,"Bảo hành sản phẩm không được chứa chữ cái và phải là số dương!");
                        jTextField5.requestFocus();
                    }
                else
                        if(jTextField5.getText().trim().equals("")){
                        JOptionPane.showMessageDialog(this, "Bảo hành không được rỗng!");
                        jTextField3.requestFocus();
                    }
                        else
                    {
                       
                        sp.setMaSanpham(jTextField1.getText());
                        sp.setTenSanpham(jTextField2.getText());
                        sp.setSoluongSanpham(parseInt(jTextField3.getText()));
                        sp.setDongiaSanpham(parseLong(jTextField4.getText()));
                        sp.setBaohanhSanpham(parseInt(jTextField5.getText()));
                         Model.addRow(new Object[]{
           jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jTextField5.getText()
       });
                       
                    
                    }
                    try{
                        hhb.them(sp);
                    } catch (Exception ex){
                        Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
           }catch (Exception ex) {
                 Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
             }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
           Model = (DefaultTableModel) jTable1.getModel();
        
        hanghoaBUS bus = new hanghoaBUS();
        
        int vitri = jTable1.getSelectedRow();
            
        if(vitri == -1) 
           JOptionPane.showMessageDialog(null, "Chưa chọn dòng cần xóa!");
        else{
            if(JOptionPane.showConfirmDialog(null,"Bạn muốn xóa sản phẩm này?","Xác nhận xóa",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION ){
           Model.removeRow(vitri);

                try {
                    bus.xoa(vitri);
                } catch (Exception ex) {
                    Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       chitietsanpham ct = null;
        try {
            ct = new chitietsanpham();
        } catch (Exception ex) {
            Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        ct.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed
    
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:        
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");      
            show1();
          
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        hanghoaBUS hhb = new hanghoaBUS();
        Sanpham spt = new Sanpham();
        
       if("".equals(jTextField2.getText().trim())){
           JOptionPane.showMessageDialog(this,"Tên sản phẩm không được rỗng" );
            }
       
       else 
          
                                    
                try {
                    
                        if(jTextField3.getText().trim().equals("")){
                            JOptionPane.showMessageDialog(this, "Số lượng không được rỗng!");
                            jTextField3.requestFocus();
                        }
                        else
                            if(!hhb.validNumber(jTextField3.getText())){
                                JOptionPane.showMessageDialog(this,"Số lượng sản phẩm không được chứa chữ cái và phải là số dương!");
                                jTextField3.requestFocus();
                            }
                            else
                                if(jTextField4.getText().trim().equals("")){
                                    JOptionPane.showMessageDialog(this, "Số lượng không được rỗng!");
                                    jTextField4.requestFocus();
                                }
                                else
                                    if(!hhb.validNumber(jTextField4.getText())){
                                        JOptionPane.showMessageDialog(this,"Đơn giá sản phẩm không được chứa chữ cái và phải là số dương!");
                                        jTextField4.requestFocus();
                                    }
                                    else
                                        if(!hhb.validNumber(jTextField5.getText())){
                                            JOptionPane.showMessageDialog(this,"Bảo hành sản phẩm không được chứa chữ cái và phải là số dương!");
                                            jTextField5.requestFocus();
                                        }
                                        else
                                            if(jTextField5.getText().trim().equals("")){
                                                JOptionPane.showMessageDialog(this, "Bảo hành không được rỗng!");
                                                jTextField3.requestFocus();
                                            }
                                            else
                                            {
                                                
                                                spt.setMaSanpham(jTextField1.getText());
                                                spt.setTenSanpham(jTextField2.getText());
                                                spt.setSoluongSanpham(parseInt(jTextField3.getText()));
                                                spt.setDongiaSanpham(parseLong(jTextField4.getText()));
                                                spt.setBaohanhSanpham(parseInt(jTextField5.getText()));
                                                
                                                
                                            }
        } catch (Exception ex) {
            Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
        }
                try{
                    hhb.sua(spt);
                      Vector header = new Vector();
        header.add("Mã sản phẩm");
        header.add("Tên sản phẩm");
        header.add("Số lượng");
        header.add("Đơn giá");
        header.add("Bảo hành");
        
        Model = new DefaultTableModel(header,0);
        for(Sanpham sp: hanghoaBUS.getDSSP()){
            Vector row = new Vector();
            row.add(sp.getMaSanpham());
            row.add(sp.getTenSanpham());
            row.add(sp.getSoluongSanpham());
            row.add(sp.getDongiaSanpham());
            row.add(sp.getBaohanhSanpham());
            Model.addRow(row);
        }
        jTable1.setModel(Model);
                }catch (Exception ex){
                        Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
                    }
            
             
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         process(false);
       this.jButton2.setEnabled(true);
       this.jTextField1.setText(null);
       this.jTextField2.setText(null);
       this.jTextField3.setText(null);
       this.jTextField4.setText(null);
       this.jTextField5.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        hanghoaBUS bus = new hanghoaBUS();
        ArrayList<Sanpham> KQ = new ArrayList<>();
        if(hanghoaBUS.getDSSP()==null)
            try{
                bus.docDSSP();
            } catch (Exception ex) {
                Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            String key = jTextField6.getText();
            if(key.trim().equals("")){
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã hoặc Tên Sản Phẩm cần tìm");
                }
            try{
                
                
                KQ = bus.timKiemTheoMaTenSP(key);
            } catch (Exception ex) {
                Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Vector header = new Vector();
            header.add("Mã sản phẩm");
            header.add("Tên sản phẩm");
            header.add("Số lượng");
            header.add("Đơn giá");
            header.add("Bảo hành");
            
            Model = new DefaultTableModel(header,0);
            for(Sanpham sp : KQ){
            Vector row = new Vector();
            row.add(sp.getMaSanpham());
            row.add(sp.getTenSanpham());
            row.add(sp.getSoluongSanpham());
            row.add(sp.getDongiaSanpham());
            row.add(sp.getBaohanhSanpham());
          
            Model.addRow(row);
            }
        jTable1.setModel(Model);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        hanghoa h = null;
        try{
            h = new hanghoa();
        }catch (Exception ex){
           java.util.logging.Logger.getLogger(hanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 
        }
        this.setVisible(false);
        h.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new hanghoa().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    void setVisable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
