/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bus.ChiTietBUS;
import Model.KhachHangDTO;
import Model.HoaDonDTO;
import bus.HoaDonBUS;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import bus.KhachHangBUS;
import dao.KhachHangDAO;
import Model.ChiTietDTO;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import bus.NhanvienBUS;
import Model.Nhanvien;

/**
 *
 * @author huynh
 */
public class HoaDon extends javax.swing.JFrame {
    ArrayList<KhachHangDTO> kh=new ArrayList<>();
    ArrayList<Nhanvien> nv=new ArrayList<>();
    ArrayList<HoaDonDTO> hd=new ArrayList<>();
    ArrayList<ChiTietDTO> ct=new ArrayList<>();
    DefaultTableModel model=new DefaultTableModel();
    DefaultTableModel model2=new DefaultTableModel();
    KhachHangBUS khbus=new KhachHangBUS();
    NhanvienBUS nvbus=new NhanvienBUS();
    Vector vector=new Vector();
    Vector vector1=new Vector();

    /**
     * Creates new form HoaDon
     */
    public HoaDon() throws Exception {
        initComponents();
        kh=khbus.dockhachhang();
        for(KhachHangDTO dto :kh){
            vector.add(dto.getMa());
        }
        cb1.setModel(new DefaultComboBoxModel(vector));
        
        nv=nvbus.docnhanvien();
        for(Nhanvien dto1 :nv){
            vector1.add(dto1.getMaNhanvien());
        }
        cb2.setModel(new DefaultComboBoxModel(vector1));
        
        load();
        load2();
       btDelete.setEnabled(false);
       btRepair.setEnabled(false);
                  
                
    }
    public void load() throws Exception{
        HoaDonBUS bus=new HoaDonBUS();
        bus.dochoadon();
        Vector header=new Vector();
        header.add("MÃ KH");
        header.add("MÃ HD");
        header.add("MÃ NV");
        header.add("LẬP");
        header.add("GIAO");
        model=new DefaultTableModel(header,0);
        for(HoaDonDTO hd: HoaDonBUS.hd){
           Vector row=new Vector();
           row.add(hd.getMaKH());
           row.add(hd.getMaHD());
           row.add(hd.getMaNV());
           row.add(hd.getNgayNhan());
           row.add(hd.getNgayGiao());
           model.addRow(row);
        }
        jTable2.setModel(model);
    }
    public void load2() throws Exception{
        ChiTietBUS bus=new ChiTietBUS();
        bus.docchitiet();
        Vector header=new Vector();
        header.add("MÃ HD");
        header.add("MÃ SP");
        header.add("Số LƯỢNG");
        header.add("ĐƠN GIÁ");
        header.add("THÀNH TIỀN");
        model2=new DefaultTableModel(header,0);
        for(ChiTietDTO chitiet: ChiTietBUS.ct){
           Vector row=new Vector();
           row.add(chitiet.getMaHD());
           row.add(chitiet.getMaSP());
           row.add(chitiet.getSL());
           row.add(chitiet.getDonGia());
           row.add(chitiet.getTT());
           model2.addRow(row);
        }
        jTable1.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        p2 = new javax.swing.JPanel();
        lbMaHd = new javax.swing.JLabel();
        lbMaNv = new javax.swing.JLabel();
        lbMaKh = new javax.swing.JLabel();
        lbNg = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        txNg = new javax.swing.JTextField();
        txMaHd = new javax.swing.JTextField();
        btDelete = new javax.swing.JButton();
        btRepair = new javax.swing.JButton();
        btFind = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        txNn1 = new javax.swing.JTextField();
        lbNn1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cb2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lbThongtin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p2.setForeground(new java.awt.Color(255, 0, 153));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMaHd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMaHd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMaHd.setText("Mã Hóa Đơn");
        lbMaHd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        p2.add(lbMaHd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 91, 31));

        lbMaNv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMaNv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMaNv.setText("Mã Nhân Viên");
        lbMaNv.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        p2.add(lbMaNv, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 91, 31));

        lbMaKh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMaKh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMaKh.setText("Mã Khách Hàng");
        lbMaKh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        p2.add(lbMaKh, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 91, 31));

        lbNg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNg.setText("Ngày Giao");
        lbNg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        p2.add(lbNg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 91, 31));

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        p2.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 120, -1));

        txNg.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txNg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p2.add(txNg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, -1));

        txMaHd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txMaHd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p2.add(txMaHd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 120, -1));

        btDelete.setBackground(new java.awt.Color(255, 0, 153));
        btDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Delete.png"))); // NOI18N
        btDelete.setText("Xoá");
        btDelete.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        p2.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, 63));

        btRepair.setBackground(new java.awt.Color(255, 0, 153));
        btRepair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Change.png"))); // NOI18N
        btRepair.setText("Sửa");
        btRepair.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRepairActionPerformed(evt);
            }
        });
        p2.add(btRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 100, 62));

        btFind.setBackground(new java.awt.Color(255, 0, 153));
        btFind.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btFind.setForeground(new java.awt.Color(255, 255, 255));
        btFind.setText("Tìm kiếm");
        btFind.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindActionPerformed(evt);
            }
        });
        p2.add(btFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 100, 20));

        btAdd.setBackground(new java.awt.Color(255, 0, 153));
        btAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Add.png"))); // NOI18N
        btAdd.setText("Thêm");
        btAdd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        p2.add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 63));

        txNn1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txNn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txNn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNn1ActionPerformed(evt);
            }
        });
        p2.add(txNn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 120, -1));

        lbNn1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNn1.setText("Ngày Nhận ");
        lbNn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        p2.add(lbNn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 91, 31));
        p2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 161, 20));

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        p2.add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 120, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Refresh-icon.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        p2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 100, 60));

        jButton3.setBackground(new java.awt.Color(255, 0, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Save.png"))); // NOI18N
        jButton3.setText("Thêm chi tiết");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        p2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 110, 60));

        p1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 670, 210));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 0, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃHD", "MÃSP", "SL", "ĐƠNGIÁ", "THÀNHTIỀN"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jScrollPane1.setViewportView(jTable1);

        p1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 500, 149));

        jTable2.setBackground(new java.awt.Color(102, 102, 102));
        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 0, 153));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        p1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 500, 149));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbThongtin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbThongtin.setForeground(new java.awt.Color(255, 0, 153));
        lbThongtin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongtin.setText("Hoá đơn");
        lbThongtin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153)));
        jPanel2.add(lbThongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 410, 80));

        jButton1.setBackground(new java.awt.Color(255, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Back.png"))); // NOI18N
        jButton1.setText("Hệ thống");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 207, 81));

        p1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        trangchu ct = new trangchu();
        this.setVisible(false);
        ct.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        btDelete.setEnabled(true);
       btRepair.setEnabled(true);
       btAdd.setEnabled(false);
        int  i=jTable2.getSelectedRow();
        if (i>=0)
        {
            cb1.setSelectedItem(jTable2.getModel().getValueAt(i, 0).toString());
            txMaHd.setText(jTable2.getModel().getValueAt(i, 1).toString());
            cb2.setSelectedItem(jTable2.getModel().getValueAt(i, 2).toString());
            txNn1.setText(jTable2.getModel().getValueAt(i, 3).toString());
            txNg.setText(jTable2.getModel().getValueAt(i, 4).toString());
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void txNn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNn1ActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        HoaDonDTO hoaddon=new HoaDonDTO();
        hoaddon.setMaKH(cb1.getSelectedItem().toString());
        hoaddon.setMaHD(txMaHd.getText());
        hoaddon.setMaNV(cb2.getSelectedItem().toString());
        hoaddon.setNgayNhan(txNn1.getText());
        hoaddon.setNgayGiao(txNg.getText());
        HoaDonBUS bus=new HoaDonBUS();
        try {
            bus.them(hoaddon);
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        Vector header=new Vector();
        header.add("MÃ KH");
        header.add("MÃ HD");
        header.add("MÃ NV");
        header.add("LẬP");
        header.add("GIAO");

        Vector rc=new Vector();
        rc.add(hoaddon.getMaKH());
        rc.add(hoaddon.getMaHD());
        rc.add(hoaddon.getMaNV());
        rc.add(hoaddon.getNgayNhan());
        rc.add(hoaddon.getNgayGiao());

        model.addRow(rc);
        jTable2.setModel(model);
        try {
            load();
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindActionPerformed
        // TODO add your handling code here:
         HoaDonBUS bus = new HoaDonBUS();
        ArrayList<HoaDonDTO> KQ = new ArrayList<>();
        if(HoaDonBUS.getHD()==null)
            try{
                bus.dochoadon();
            } catch (Exception ex) {
                Logger.getLogger(nhanvien.class.getName()).log(Level.SEVERE, null, ex);
            }
            String key = jTextField1.getText();
            if(key.trim().equals("")){
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã hoặc Tên Sản Phẩm cần tìm");
                }
            try{
                
                
                KQ = bus.timKiemTheoMaTenSP(key);
            } catch (Exception ex) {
                Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            Vector header = new Vector();        
             header.add("MÃ HD");
             header.add("MÃ KH");
                header.add("MÃ NV");
                header.add("LẬP");
                header.add("GIAO");

            
            model = new DefaultTableModel(header,0);
            for(HoaDonDTO sp : KQ){
            Vector row = new Vector();
            row.add(sp.getMaHD());
            row.add(sp.getMaKH());
            row.add(sp.getMaNV());
            row.add(sp.getNgayNhan());
            row.add(sp.getNgayGiao());

          
            model.addRow(row);
            }
        jTable2.setModel(model);
                                      
    }//GEN-LAST:event_btFindActionPerformed

    private void btRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRepairActionPerformed
        // TODO add your handling code here:

        HoaDonDTO hd=new HoaDonDTO();
        hd.setMaKH(cb1.getSelectedItem().toString());
        hd.setMaHD(txMaHd.getText());
        hd.setMaNV(cb2.getSelectedItem().toString());
        hd.setNgayNhan(txNn1.getText());
        hd.setNgayGiao(txNg.getText());
        HoaDonBUS bus=new  HoaDonBUS();
        try {
            bus.sua(hd);
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            load();
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRepairActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        model = (DefaultTableModel) jTable2.getModel();

        HoaDonBUS bus = new HoaDonBUS();

        int vitri = jTable2.getSelectedRow();

        if(vitri == -1)
        JOptionPane.showMessageDialog(null, "Chưa chọn dòng cần xóa!");
        else{
            if(JOptionPane.showConfirmDialog(null,"Bạn muốn xóa sản phẩm này?","Xác nhận xóa",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION ){
                model.removeRow(vitri);

                try {
                    bus.xoa(vitri);
                } catch (Exception ex) {
                    Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txMaHd.setText("");
        txNg.setText("");
        txNn1.setText("");
        jTextField1.setText("");
        btDelete.setEnabled(false);
       btRepair.setEnabled(false);
       btAdd.setEnabled(true);
        try {
            load();
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HoaDon().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btFind;
    private javax.swing.JButton btRepair;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbMaHd;
    private javax.swing.JLabel lbMaKh;
    private javax.swing.JLabel lbMaNv;
    private javax.swing.JLabel lbNg;
    private javax.swing.JLabel lbNn1;
    private javax.swing.JLabel lbThongtin;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JTextField txMaHd;
    private javax.swing.JTextField txNg;
    private javax.swing.JTextField txNn1;
    // End of variables declaration//GEN-END:variables
}
