/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Model.KhachHangDTO;
import java.util.Vector;
import bus.KhachHangBUS;
import dao.KhachHangDAO;
import com.mysql.cj.xdevapi.Table;
import java.awt.Component;
import java.awt.geom.Arc2D;
import java.sql.SQLException;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author huynh
 */
public class KhachHang extends javax.swing.JFrame {
    ArrayList<KhachHangDTO> kh=new ArrayList<>();
    DefaultTableModel model=new DefaultTableModel();
    
 
 
    /**
     * Creates new form KhachHang
     */
    public KhachHang() throws Exception {
        initComponents();
        model=(DefaultTableModel) tbl.getModel();
        load();
    }
    public void load() throws Exception{
        KhachHangBUS bus=new KhachHangBUS();
        bus.dockhachhang();
        Vector header=new Vector();
        header.add("Tên");
        header.add("Mã KH");
        header.add("Số điện thoại");
        header.add("Địa chỉ");
        model=new DefaultTableModel(header,0);
        for(KhachHangDTO kh: KhachHangBUS.kh){
           Vector row=new Vector();
           row.add(kh.getTen());
           row.add(kh.getMa());
           row.add(kh.getPhone());
           row.add(kh.getAddress());
           model.addRow(row);
        }
        tbl.setModel(model);
        btDelete.setEnabled(false);
        btReset.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbThongtin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        p2 = new javax.swing.JPanel();
        lbTen = new javax.swing.JLabel();
        lbMa = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        txTen = new javax.swing.JTextField();
        txMA = new javax.swing.JTextField();
        txAddress = new javax.swing.JTextField();
        txPhone = new javax.swing.JTextField();
        lbPhone = new javax.swing.JLabel();
        btTim = new javax.swing.JButton();
        txFind = new javax.swing.JTextField();
        p4 = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        btFind = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p1.setForeground(new java.awt.Color(255, 0, 153));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbThongtin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbThongtin.setForeground(new java.awt.Color(255, 0, 153));
        lbThongtin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongtin.setText("THÔNG TIN KHÁCH HÀNG");
        lbThongtin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153)));
        jPanel2.add(lbThongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 670, 80));

        jButton1.setBackground(new java.awt.Color(255, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Back.png"))); // NOI18N
        jButton1.setText("Hệ thống");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 207, 81));

        lbTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTen.setText("Tên khách hàng");
        lbTen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbMa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMa.setText("Mã KH");
        lbMa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbAddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAddress.setText("Địa chỉ");
        lbAddress.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txTen.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txTen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txMA.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txMA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txAddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAddressActionPerformed(evt);
            }
        });

        txPhone.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txPhone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPhoneActionPerformed(evt);
            }
        });

        lbPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPhone.setText("Số điện thoại");
        lbPhone.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btTim.setBackground(new java.awt.Color(255, 0, 153));
        btTim.setText("Tìm kiếm");
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });

        txFind.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txFind.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(lbMa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btTim, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txTen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txMA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txFind, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTen))
                .addGap(27, 27, 27)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txMA))
                .addGap(29, 29, 29)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTim)
                    .addComponent(txFind))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        p4.setForeground(new java.awt.Color(127, 160, 221));
        p4.setMinimumSize(new java.awt.Dimension(100, 200));
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAdd.setBackground(new java.awt.Color(255, 0, 153));
        btAdd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Add.png"))); // NOI18N
        btAdd.setText("Thêm");
        btAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btReset.setBackground(new java.awt.Color(255, 0, 153));
        btReset.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Change.png"))); // NOI18N
        btReset.setText("Sửa");
        btReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        btFind.setBackground(new java.awt.Color(255, 0, 153));
        btFind.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Refresh-icon.png"))); // NOI18N
        btFind.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindActionPerformed(evt);
            }
        });

        btDelete.setBackground(new java.awt.Color(255, 0, 153));
        btDelete.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Delete.png"))); // NOI18N
        btDelete.setText("Xoá");
        btDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        tbl.setAutoCreateRowSorter(true);
        tbl.setBackground(new java.awt.Color(102, 102, 102));
        tbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl.setForeground(new java.awt.Color(255, 0, 153));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TÊN", "MÃ", "PHONE", "Address"
            }
        ));
        tbl.setSelectionBackground(new java.awt.Color(0, 0, 51));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btFind, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(btDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(51, Short.MAX_VALUE))))
        );

        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed

        KhachHangDTO khachHangDTO=new KhachHangDTO();
        khachHangDTO.setTen(txTen.getText());
        khachHangDTO.setMa(txMA.getText());
        khachHangDTO.setPhone(txPhone.getText());
        khachHangDTO.setAddress(txAddress.getText());
        kh.add(khachHangDTO);
        KhachHangBUS bus=new  KhachHangBUS();
        try {
            bus.them(khachHangDTO);
        } catch (Exception ex) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        Vector header=new Vector();

        header.add("Tên");
        header.add("Mã KH");
        header.add("Số điện thoại");
        header.add("Địa chỉ");
        model=new DefaultTableModel(header,0);
        Vector rc=new Vector();
        rc.add(khachHangDTO.getTen());
        rc.add(khachHangDTO.getMa());
        rc.add(khachHangDTO.getPhone());
        rc.add(khachHangDTO.getAddress());
        model.addRow(rc);
        tbl.setModel(model);
        try {
            load();
        } catch (Exception ex) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
 
    }//GEN-LAST:event_btAddActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
       
        KhachHangDTO khachHangDTO=new KhachHangDTO();
        khachHangDTO.setTen(txTen.getText());
        khachHangDTO.setMa(txMA.getText());
        khachHangDTO.setPhone(txPhone.getText());
        khachHangDTO.setAddress(txAddress.getText());
        KhachHangBUS bus=new  KhachHangBUS();
        try {
            bus.sua(khachHangDTO);
        } catch (Exception ex) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            load();
        } catch (Exception ex) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btResetActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) tbl.getModel();
        
        KhachHangBUS bus = new KhachHangBUS();
        
        int vitri = tbl.getSelectedRow();
            
        if(vitri == -1) 
           JOptionPane.showMessageDialog(null, "Chưa chọn dòng cần xóa!");
        else{
            if(JOptionPane.showConfirmDialog(null,"Bạn muốn xóa sản phẩm này?","Xác nhận xóa",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION ){
           model.removeRow(vitri);

                try {
                    bus.xoa(vitri);
                } catch (Exception ex) {
                    Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        btReset.setEnabled(true);
        btDelete.setEnabled(true);
        int  i=tbl.getSelectedRow();
        if (i>=0)
        {

            txTen.setText(tbl.getModel().getValueAt(i, 0).toString());
            txMA.setText(tbl.getModel().getValueAt(i, 1).toString());
            txPhone.setText(tbl.getModel().getValueAt(i, 2).toString());
            txAddress.setText(tbl.getModel().getValueAt(i, 3).toString());

        }  
        this.txMA.setEnabled(false);
    }//GEN-LAST:event_tblMouseClicked

    private void btFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindActionPerformed
        // TODO add your handling code here:
        txTen.setText("");
        txMA.setText("");
        txPhone.setText("");
        txAddress.setText("");
        txFind.setText("");
        btReset.setEnabled(false);
        btDelete.setEnabled(false);
         txMA.setEnabled(true);
        try {
            load();
        } catch (Exception ex) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btFindActionPerformed

    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed
        // TODO add your handling code here:
        KhachHangBUS bus = new KhachHangBUS();
        ArrayList<KhachHangDTO> KQ = new ArrayList<>();
        if(KhachHangBUS.getKH()==null)
        try{
            bus.dockhachhang();
        } catch (Exception ex) {
            Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
        }
        String key = txFind.getText();
        if(key.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã hoặc Tên Sản Phẩm cần tìm");
        }
        try{

            KQ = bus.timKiemTheoMaTenSP(key);
        } catch (Exception ex) {
            Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
        }

        Vector header = new Vector();
        header.add("Tên");
        header.add("Mã");
        header.add("Số điện thoại");
        header.add("Địa chỉ");

        model = new DefaultTableModel(header,0);
        for(KhachHangDTO hk : KQ){
            Vector row = new Vector();
            row.add(hk.getTen());
            row.add(hk.getMa());
            row.add(hk.getPhone());
            row.add(hk.getAddress());

            model.addRow(row);
        }
        tbl.setModel(model);
    }//GEN-LAST:event_btTimActionPerformed

    private void txPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPhoneActionPerformed

    private void txAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txAddressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        trangchu ct = new trangchu();
        this.setVisible(false);
        ct.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KhachHang().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btFind;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTim;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbMa;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbTen;
    private javax.swing.JLabel lbThongtin;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p4;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txAddress;
    private javax.swing.JTextField txFind;
    private javax.swing.JTextField txMA;
    private javax.swing.JTextField txPhone;
    private javax.swing.JTextField txTen;
    // End of variables declaration//GEN-END:variables
}
