/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Model.Nhanvien;
import bus.NhanvienBUS;
import static java.lang.Long.parseLong;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class nhanvien extends javax.swing.JFrame {
        DefaultTableModel Model;
    /**
     * Creates new form nhanvien
     */
    public nhanvien() throws Exception {
        initComponents();
        process(false);
         NhanvienBUS bus = new NhanvienBUS();
        if(NhanvienBUS.getDSNV()==null)
           bus.docDSNV();
       Vector header = new Vector();
        header.add("Mã nhân viên");
        header.add("Họ nhân viên");
        header.add("Tên nhân viên");
        header.add("Chức vụ");
        header.add("Lương");
        header.add("Số điện thoại");
        
        Model = new DefaultTableModel(header,0);
        for(Nhanvien sp: NhanvienBUS.getDSNV()){
            Vector row = new Vector();
            row.add(sp.getMaNhanvien());
            row.add(sp.getHoNhanvien());
            row.add(sp.getTenNhanvien());
            row.add(sp.getChucvuNhanvien());
            row.add(sp.getLuongNhanvien());
            row.add(sp.getSdtNhanvien());
            Model.addRow(row);
        }
        jTable1.setModel(Model);
    }
    public void process(boolean b){
      this.jButton2.setEnabled(b);
      this.jButton7.setEnabled(b);
      this.jButton8.setEnabled(b);
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField7 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Refresh-icon.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Back.png"))); // NOI18N
        jButton1.setText("Hệ thống");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, 204, 93));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã nhân viên:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 126, 32));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Họ nhân viên:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, 30));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 124, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tên nhân viên: ");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 130, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 171, 31));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Chức vụ:");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, 30));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 126, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Lương:");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 65, 30));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 164, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Số điện thoại:");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, -1, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 171, 33));

        jButton12.setBackground(new java.awt.Color(255, 0, 153));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Refresh-icon.png"))); // NOI18N
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 120, 93));

        jButton2.setBackground(new java.awt.Color(255, 0, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Add.png"))); // NOI18N
        jButton2.setText("Thêm");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 120, 93));

        jButton7.setBackground(new java.awt.Color(255, 0, 153));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Change.png"))); // NOI18N
        jButton7.setText("Sửa");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 120, 93));

        jButton8.setBackground(new java.awt.Color(255, 0, 153));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Delete.png"))); // NOI18N
        jButton8.setText("Xoá");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 120, 96));

        jButton3.setBackground(new java.awt.Color(255, 0, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Nhập mới");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 40));

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setForeground(new java.awt.Color(255, 0, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ nhân viên", "Tên nhân viên", "Chức vụ", "Lương", "Số điện thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setDragEnabled(true);
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 650, 270));

        jTextField7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 596, 29));

        jButton4.setBackground(new java.awt.Color(255, 0, 153));
        jButton4.setText("Tìm kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, -1, 39));

        jButton5.setBackground(new java.awt.Color(255, 0, 153));
        jButton5.setText("Quay lại");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, -1, 40));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 0, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý nhân viên");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         trangchu ct = new trangchu();
        this.setVisible(false);
        ct.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         process(false);
       this.jButton2.setEnabled(true);
       this.jTextField1.setText(null);
       this.jTextField2.setText(null);
       this.jTextField3.setText(null);
       this.jTextField4.setText(null);
       this.jTextField5.setText(null);
       this.jTextField6.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed
     public void show1(){
        process(false);
       this.jButton2.setEnabled(false);
       this.jTextField1.setText(null);
       this.jTextField2.setText(null);
       this.jTextField3.setText(null);
       this.jTextField4.setText(null);
       this.jTextField5.setText(null);
    }
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");      
            jTextField6.setText("");   
            show1();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NhanvienBUS hhb = new NhanvienBUS();
       Nhanvien sp = new Nhanvien();
      
       if("".equals(jTextField1.getText().trim())){
           JOptionPane.showMessageDialog(this, "Mã nhân viên không được rỗng");
           jTextField1.requestFocus();
       }
       
       else 
          try{
              if(!hhb.vaildID(jTextField1.getText())){
              JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại");    
              }
              else
                  if("".equals(jTextField2.getText().trim())){
                    JOptionPane.showMessageDialog(this, "Họ nhân viên không được rỗng");    
                  }
                  else
                      if("".equals(jTextField3.getText().trim())){
                    JOptionPane.showMessageDialog(this, "Tên nhân viên không được rỗng");    
                  }
                      else
                          if("".equals(jTextField4.getText().trim())){
                    JOptionPane.showMessageDialog(this, "Chức vụ không được rỗng");    
                  }
                          else
                              if(jTextField4.getText()=="Quản lý"){
                    JOptionPane.showMessageDialog(this, "Chỉ có một quản lý");    
                  }
                              else
                                   if("".equals(jTextField5.getText().trim())){
                        JOptionPane.showMessageDialog(this, "Lương không được rỗng");    
                  }
                                   else
                                       if(!hhb.validNumber(jTextField5.getText())){
                        JOptionPane.showMessageDialog(this, "Lương không được là chữ hoặc số âm");    
                  }
                                       else
                                           if("".equals(jTextField6.getText().trim())){
                        JOptionPane.showMessageDialog(this, "Số điện thoại không được rỗng");    
                  }
                                           else
                                               if(!hhb.validNumber(jTextField6.getText())){
                        JOptionPane.showMessageDialog(this, "Số điện thoại không được là chữ hoặc số âm");    
                  }
                        else
                    {
                       
                        sp.setMaNhanvien(jTextField1.getText());
                        sp.setHoNhanvien(jTextField2.getText());
                        sp.setTenNhanvien(jTextField3.getText());
                        sp.setChucvuNhanvien(jTextField4.getText());
                        sp.setLuongNhanvien(parseLong(jTextField5.getText()));
                        sp.setSdtNhanvien(parseLong(jTextField5.getText()));
                         Model.addRow(new Object[]{
           jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText()
       });
                       
                    
                    }
                    try{
                        hhb.them(sp);
                    } catch (Exception ex){
                        Logger.getLogger(nhanvien.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
           }catch (Exception ex) {
                 Logger.getLogger(nhanvien.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         NhanvienBUS hhb = new NhanvienBUS();
        Nhanvien spt = new Nhanvien();
        
       if("".equals(jTextField2.getText().trim())){
           JOptionPane.showMessageDialog(this,"Tên sản phẩm không được rỗng" );
            }
       
       else 
          
                                    
                try {
                     
                  if("".equals(jTextField2.getText().trim())){
                    JOptionPane.showMessageDialog(this, "Họ nhân viên không được rỗng");    
                  }
                  else
                      if("".equals(jTextField3.getText().trim())){
                    JOptionPane.showMessageDialog(this, "Tên nhân viên không được rỗng");    
                  }
                      else
                          if("".equals(jTextField4.getText().trim())){
                    JOptionPane.showMessageDialog(this, "Chức vụ không được rỗng");    
                  }
                          else
                              if(jTextField4.getText()=="Quản lý"){
                    JOptionPane.showMessageDialog(this, "Chỉ có một quản lý");    
                  }
                              else
                                   if("".equals(jTextField5.getText().trim())){
                        JOptionPane.showMessageDialog(this, "Lương không được rỗng");    
                  }
                                   else
                                       if(!hhb.validNumber(jTextField5.getText())){
                        JOptionPane.showMessageDialog(this, "Lương không được là chữ hoặc số âm");    
                  }
                                       else
                                           if("".equals(jTextField6.getText().trim())){
                        JOptionPane.showMessageDialog(this, "Số điện thoại không được rỗng");    
                  }
                                           else
                                               if(!hhb.validNumber(jTextField6.getText())){
                        JOptionPane.showMessageDialog(this, "Số điện thoại không được là chữ hoặc số âm");    
                  }
                                            {
                                                
                        spt.setMaNhanvien(jTextField1.getText());
                        spt.setHoNhanvien(jTextField2.getText());
                        spt.setTenNhanvien(jTextField3.getText());
                        spt.setChucvuNhanvien(jTextField4.getText());
                        spt.setLuongNhanvien(parseLong(jTextField5.getText()));
                        spt.setSdtNhanvien(parseLong(jTextField5.getText()));
                                                
                                                
                                            }
        } catch (Exception ex) {
            Logger.getLogger(nhanvien.class.getName()).log(Level.SEVERE, null, ex);
        }
                try{
                    hhb.sua(spt);
        Vector header = new Vector();        
        header.add("Mã nhân viên");
        header.add("Họ nhân viên");
        header.add("Tên nhân viên");
        header.add("Chức vụ");
        header.add("Lương");
        header.add("Số điện thoại");
        
        Model = new DefaultTableModel(header,0);
        for(Nhanvien sp: NhanvienBUS.getDSNV()){
            Vector row = new Vector();
            row.add(sp.getMaNhanvien());
            row.add(sp.getHoNhanvien());
            row.add(sp.getTenNhanvien());
            row.add(sp.getChucvuNhanvien());
            row.add(sp.getLuongNhanvien());
            row.add(sp.getSdtNhanvien());
            Model.addRow(row);
        }
        jTable1.setModel(Model);
                }catch (Exception ex){
                        Logger.getLogger(nhanvien.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        process(true);
        this.jButton2.setEnabled(false);
         this.jTextField1.setEnabled(false);
     int row = jTable1.getSelectedRow();
       String id = jTable1.getValueAt(row,0).toString();
       String ho = jTable1.getValueAt(row,1).toString();
       String ten = jTable1.getValueAt(row,2).toString();
       String cv = jTable1.getValueAt(row,3).toString();
       String luong = jTable1.getValueAt(row,4).toString();
       String sdt = jTable1.getValueAt(row,5).toString();
       
        
        jTextField1.setText(id);
        jTextField2.setText(ho);
        jTextField3.setText(ten);
        jTextField4.setText(cv);
        jTextField5.setText(luong);
        jTextField6.setText(sdt);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Model = (DefaultTableModel) jTable1.getModel();
        
        NhanvienBUS bus = new NhanvienBUS();
        
        int vitri = jTable1.getSelectedRow();
            
        if(vitri == -1) 
           JOptionPane.showMessageDialog(null, "Chưa chọn dòng cần xóa!");
        else{
            if(JOptionPane.showConfirmDialog(null,"Bạn muốn xóa sản phẩm này?","Xác nhận xóa",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION ){
           Model.removeRow(vitri);

                try {
                    bus.xoa(vitri);
                } catch (Exception ex) {
                    Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        NhanvienBUS bus = new NhanvienBUS();
        ArrayList<Nhanvien> KQ = new ArrayList<>();
        if(NhanvienBUS.getDSNV()==null)
            try{
                bus.docDSNV();
            } catch (Exception ex) {
                Logger.getLogger(nhanvien.class.getName()).log(Level.SEVERE, null, ex);
            }
            String key = jTextField7.getText();
            if(key.trim().equals("")){
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã hoặc Tên Sản Phẩm cần tìm");
                }
            try{
                
                
                KQ = bus.timKiemTheoMaTenSP(key);
            } catch (Exception ex) {
                Logger.getLogger(hanghoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            Vector header = new Vector();        
             header.add("Mã nhân viên");
             header.add("Họ nhân viên");
                header.add("Tên nhân viên");
                header.add("Chức vụ");
                header.add("Lương");
                 header.add("Số điện thoại");
            
            Model = new DefaultTableModel(header,0);
            for(Nhanvien sp : KQ){
            Vector row = new Vector();
            row.add(sp.getMaNhanvien());
            row.add(sp.getHoNhanvien());
            row.add(sp.getTenNhanvien());
            row.add(sp.getChucvuNhanvien());
            row.add(sp.getLuongNhanvien());
            row.add(sp.getSdtNhanvien());
          
            Model.addRow(row);
            }
        jTable1.setModel(Model);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         nhanvien h = null;
        try{
            h = new nhanvien();
        }catch (Exception ex){
           java.util.logging.Logger.getLogger(hanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 
        }
        this.setVisible(false);
        h.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new nhanvien().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(nhanvien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
